const scienceQuestions = [
  {
    id: 1,
    questionText: "What is the theoretical maximum density of a black hole?",
    choices: ["1 g/cm³", "1,000 g/cm³", "Infinite", "100 g/cm³"],
    correctAnswer: "Infinite",
  },
  {
    id: 2,
    questionText: "Who is known as the 'Father of Modern Physics'?",
    choices: ["Isaac Newton", "Galileo Galilei", "Albert Einstein", "Niels Bohr"],
    correctAnswer: "Albert Einstein",
  },
  {
    id: 3,
    questionText: "Which planet is known as the 'Red Planet'?",
    choices: ["Mars", "Venus", "Jupiter", "Saturn"],
    correctAnswer: "Mars",
  },
  {
    id: 4,
    questionText: "What year did the Titanic sink?",
    choices: ["1912", "1905", "1920", "1931"],
    correctAnswer: "1912",
  },
  {
    id: 5,
    questionText: "What is the capital city of Japan?",
    choices: ["Beijing", "Seoul", "Tokyo", "Bangkok"],
    correctAnswer: "Tokyo",
  },
  {
    id: 6,
    questionText: "What is the chemical symbol for gold?",
    choices: ["Au", "Ag", "Fe", "Cu"],
    correctAnswer: "Au",
  },
  {
    id: 7,
    questionText: "In which year did World War II end?",
    choices: ["1945", "1939", "1941", "1950"],
    correctAnswer: "1945",
  },
  {
    id: 8,
    questionText: "What is the largest mammal in the world?",
    choices: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"],
    correctAnswer: "Blue Whale",
  },
  {
    id: 9,
    questionText: "Who wrote 'Romeo and Juliet'?",
    choices: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"],
    correctAnswer: "William Shakespeare",
  },
  {
    id: 10,
    questionText: "What is the square root of 144?",
    choices: ["10", "12", "14", "16"],
    correctAnswer: "12",
  },
  {
    id: 11,
    questionText: "Which gas is most abundant in Earth's atmosphere?",
    choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"],
    correctAnswer: "Nitrogen",
  },
  {
    id: 12,
    questionText: "Who developed the theory of relativity?",
    choices: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Niels Bohr"],
    correctAnswer: "Albert Einstein",
  },
  {
    id: 13,
    questionText: "What is the smallest prime number?",
    choices: ["0", "1", "2", "3"],
    correctAnswer: "2",
  },
  {
    id: 14,
    questionText: "In what year did Christopher Columbus reach the Americas?",
    choices: ["1492", "1500", "1510", "1525"],
    correctAnswer: "1492",
  },
  {
    id: 15,
    questionText: "What is the capital city of Australia?",
    choices: ["Sydney", "Melbourne", "Canberra", "Brisbane"],
    correctAnswer: "Canberra",
  },
  {
    id: 16,
    questionText: "What is the powerhouse of the cell?",
    choices: ["Nucleus", "Mitochondria", "Endoplasmic Reticulum", "Golgi Apparatus"],
    correctAnswer: "Mitochondria",
  },
  {
    id: 17,
    questionText: "Who is the author of 'To Kill a Mockingbird'?",
    choices: ["Harper Lee", "J.K. Rowling", "George Orwell", "Ernest Hemingway"],
    correctAnswer: "Harper Lee",
  },
  {
    id: 18,
    questionText: "What is the speed of light in a vacuum?",
    choices: ["300,000 km/s", "150,000 km/s", "600,000 km/s", "900,000 km/s"],
    correctAnswer: "300,000 km/s",
  },
  {
    id: 19,
    questionText: "Which element has the chemical symbol 'H'?",
    choices: ["Helium", "Hydrogen", "Hassium", "Hafnium"],
    correctAnswer: "Hydrogen",
  },
  {
    id: 20,
    questionText: "Who was the first woman to win a Nobel Prize?",
    choices: ["Marie Curie", "Rosalind Franklin", "Jane Goodall", "Dorothy Crowfoot Hodgkin"],
    correctAnswer: "Marie Curie",
  },
  {
    id: 21,
    questionText: "What is the largest ocean on Earth?",
    choices: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
    correctAnswer: "Pacific Ocean",
  },
  {
    id: 22,
    questionText: "Which planet is known as the 'Morning Star'?",
    choices: ["Mars", "Venus", "Jupiter", "Mercury"],
    correctAnswer: "Venus",
  },
  {
    id: 23,
    questionText: "Who painted the Mona Lisa?",
    choices: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Michelangelo"],
    correctAnswer: "Leonardo da Vinci",
  },
  {
    id: 24,
    questionText: "What is the chemical symbol for water?",
    choices: ["H2O", "CO2", "O2", "N2"],
    correctAnswer: "H2O",
  },
  {
    id: 25,
    questionText: "In which year did the United States declare its independence?",
    choices: ["1776", "1789", "1800", "1812"],
    correctAnswer: "1776",
  },
  {
    id: 26,
    questionText: "What is the capital city of Brazil?",
    choices: ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador"],
    correctAnswer: "Brasilia",
  },
  {
    id: 27,
    questionText: "Who wrote 'The Great Gatsby'?",
    choices: ["F. Scott Fitzgerald", "Ernest Hemingway", "J.D. Salinger", "Mark Twain"],
    correctAnswer: "F. Scott Fitzgerald",
  },
  {
    id: 28,
    questionText: "What is the largest planet in our solar system?",
    choices: ["Earth", "Mars", "Jupiter", "Saturn"],
    correctAnswer: "Jupiter",
  },
  {
    id: 29,
    questionText: "What is the formula for the area of a triangle?",
    choices: ["A = bh/2", "A = l*w", "A = πr²", "A = 2πr"],
    correctAnswer: "A = bh/2",
  },
  {
    id: 30,
    questionText: "Who was the first President of the United States?",
    choices: ["Thomas Jefferson", "John Adams", "George Washington", "James Madison"],
    correctAnswer: "George Washington",
  },
  {
    id: 31,
    questionText: "What is the capital city of France?",
    choices: ["Berlin", "Madrid", "Paris", "Rome"],
    correctAnswer: "Paris",
  },
  {
    id: 32,
    questionText: "Which is the smallest prime number greater than 10?",
    choices: ["11", "13", "17", "19"],
    correctAnswer: "11",
  },
  {
    id: 33,
    questionText: "In what year did the Berlin Wall fall?",
    choices: ["1985", "1989", "1991", "1995"],
    correctAnswer: "1989",
  },
  {
    id: 34,
    questionText: "What is the capital city of China?",
    choices: ["Beijing", "Shanghai", "Hong Kong", "Taipei"],
    correctAnswer: "Beijing",
  },
  {
    id: 35,
    questionText: "Who is the author of '1984'?",
    choices: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "J.K. Rowling"],
    correctAnswer: "George Orwell",
  },
  {
    id: 36,
    questionText: "What is the powerhouse of a cell?",
    choices: ["Nucleus", "Mitochondria", "Ribosome", "Endoplasmic Reticulum"],
    correctAnswer: "Mitochondria",
  },
  {
    id: 37,
    questionText: "Which gas makes up the majority of Earth's atmosphere?",
    choices: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Argon"],
    correctAnswer: "Nitrogen",
  },
  {
    id: 38,
    questionText: "What is the largest bone in the human body?",
    choices: ["Femur", "Tibia", "Radius", "Humerus"],
    correctAnswer: "Femur",
  },
  {
    id: 39,
    questionText: "Who developed the theory of evolution by natural selection?",
    choices: ["Charles Darwin", "Gregor Mendel", "Louis Pasteur", "Alfred Wallace"],
    correctAnswer: "Charles Darwin",
  },
  {
    id: 40,
    questionText: "What is the chemical symbol for iron?",
    choices: ["Fe", "Au", "Ag", "Cu"],
    correctAnswer: "Fe",
  },
  {
    id: 41,
    questionText: "In what year did the Renaissance begin?",
    choices: ["1300", "1400", "1500", "1600"],
    correctAnswer: "1400",
  },
  {
    id: 42,
    questionText: "What is the largest desert in the world?",
    choices: ["Sahara Desert", "Arabian Desert", "Antarctica", "Gobi Desert"],
    correctAnswer: "Antarctica",
  },
  {
    id: 43,
    questionText: "Who wrote 'The Odyssey'?",
    choices: ["Homer", "Virgil", "Ovid", "Sophocles"],
    correctAnswer: "Homer",
  },
  {
    id: 44,
    questionText: "What is the capital city of South Korea?",
    choices: ["Seoul", "Tokyo", "Beijing", "Bangkok"],
    correctAnswer: "Seoul",
  },
  {
    id: 45,
    questionText: "What is the chemical symbol for silver?",
    choices: ["Ag", "Au", "Cu", "Fe"],
    correctAnswer: "Ag",
  },
  {
    id: 46,
    questionText: "Who is credited with the discovery of penicillin?",
    choices: ["Alexander Fleming", "Louis Pasteur", "Joseph Lister", "Marie Curie"],
    correctAnswer: "Alexander Fleming",
  },
  {
    id: 47,
    questionText: "What is the capital city of Canada?",
    choices: ["Toronto", "Vancouver", "Ottawa", "Montreal"],
    correctAnswer: "Ottawa",
  },
  {
    id: 48,
    questionText: "Who wrote 'The Catcher in the Rye'?",
    choices: ["J.D. Salinger", "Ernest Hemingway", "F. Scott Fitzgerald", "Mark Twain"],
    correctAnswer: "J.D. Salinger",
  },
  {
    id: 49,
    questionText: "What is the square of 9?",
    choices: ["72", "81", "64", "49"],
    correctAnswer: "81",
  },
  {
    id: 50,
    questionText: "Who is known as the 'Queen of Soul'?",
    choices: ["Aretha Franklin", "Whitney Houston", "Diana Ross", "Beyoncé"],
    correctAnswer: "Aretha Franklin",
  },
];


export { scienceQuestions };
